---
- name: setup server
  hosts: servers
  vars_files:
    - "vars/main.yaml"
  become: yes

  tasks:

    - name: create user cloudru with specified password
      user:
        name: "{{user}}"
        password: "{{password}}" # запрошенный пароль с солью ra1n
        create_home: yes

    - name: check if openssh server is installed and if not, install it then
      apt:
        name: 'openssh-server'
        state: present
    
    - name: disable any password methods on sshd
      shell: 
        cmd: |
          cat <<EOF | sudo tee /etc/ssh/sshd_config.d/10-ansible-setup.conf
          ChallengeResponseAuthentication no
          PasswordAuthentication no
          PermitRootLogin no
          EOF

    - name: run sshd by systemd
      systemd:
        name: sshd
        enabled: yes
        state: started
    
    - name: create .ssh directory
      file:
        path: /home/{{user}}/.ssh/
        state: directory
        owner: "{{user}}"
        group: "{{user}}"
        mode: 0755
    
    - name: touch authorized_keys
      file:
        path: /home/{{user}}/.ssh/authorized_keys
        state: touch
        owner: "{{user}}"
        group: "{{user}}"
    
    - name: set new public key for user cloudru # Честно, обратил внимание на потенциальную опечатку в последнем пункте задания, где сказано установить ключ юзеру cloudpass
      shell: |
        echo {{ssh_key}} | tee -a /home/{{user}}/.ssh/authorized_keys
        
