apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
  namespace: devops
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: "/hostname"
        backend:
          service:
            name: test-app
            port: 
              number: 8000
      - pathType: ImplementationSpecific
        path: "/id"
        backend:
          service:
            name: test-app
            port:
              number: 8000
      - pathType: ImplementationSpecific
        path: "/author"
        backend:
          service:
            name: test-app
            port:
              number: 8000  